#!/usr/bin/env bash
# argonaughts
x=1
while [ $x -lt 21 ]
do
    case $x in
	
	4)
	    echo "bad luck from China"
	    ;;

	9)
	    echo "bad luck from Japan"
	    ;;

	17)
	    echo "bad luck from Italy"
	    ;;
	*)
	    echo $x
	    ;;
    esac
    (( x++ ))
done

     
